# Generated by Django 3.1.7 on 2021-03-24 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_desc', models.TextField(blank=True)),
                ('task_taker', models.CharField(blank=True, max_length=255)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_taken', models.DateTimeField(blank=True, null=True)),
                ('time_done', models.DateTimeField(blank=True, null=True)),
                ('task_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True)),
                ('profile1', models.ImageField(blank=True, default='static/assets/img/bg5.jpg', null=True, upload_to='images/')),
                ('bgprofile', models.ImageField(blank=True, default='static/assets/img/bg5.jpg', null=True, upload_to='images/')),
                ('address', models.CharField(max_length=1000, null=True)),
                ('locatity', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
